version: '3.1'

services:
  pg:
    image: postgres:15.1
    container_name: pg
    restart: always
    environment:
      POSTGRES_DB: sport_trait_dev
      POSTGRES_USER: sport_trait_dev
      POSTGRES_PASSWORD: sport_trait_dev
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
